#!/bin/sh

python stop.py

PAXOS_TYPE=acceptor PAXOS_ID=0 python ../paxos.py &
PAXOS_TYPE=acceptor PAXOS_ID=1 python ../paxos.py &
PAXOS_TYPE=acceptor PAXOS_ID=2 python ../paxos.py &
PAXOS_TYPE=acceptor PAXOS_ID=3 python ../paxos.py &
PAXOS_TYPE=acceptor PAXOS_ID=4 python ../paxos.py &

PAXOS_TYPE=proposer PAXOS_ID=0 python ../paxos.py &
PAXOS_TYPE=proposer PAXOS_ID=1 python ../paxos.py &
PAXOS_TYPE=proposer PAXOS_ID=2 python ../paxos.py &
#PAXOS_TYPE=proposer PAXOS_ID=3 python ../paxos.py &


PAXOS_TYPE=client 	python ../paxos.py &
